class ValueTimestampTuple:
    """Container class for output generated by value workers.

    The following fields are provided:
    :param value: float = a sensor value
    :param timestamp: str = the timestamp the value was received.
                            It has the format Day.Month.Year-Hour:Minute:Second (17.12.2019-16:51:28).
    """

    def __init__(self, value: float, timestamp: str):
        """Initializes this class and stores the given values in their corresponding fields.

        :param value: float = a sensor value
        :param timestamp: str = the timestamp the value was received.
                                It has the format Day.Month.Year-Hour:Minute:Second (17.12.2019-16:51:28).
        """

        self.value = value
        self.timestamp = timestamp
